### ISSUE TITLE
issue warning if dataframe has duplicate values in row/column labels

### ISSUE THREAD

**Issue by SamLau95** [SamLau95/pandas_tutor#1]
sam:

> technically pandas indexes can have duplicate values (ugh, i know). in pathological cases 2+ rows in a dataframe can have the same label, and even 2+ columns can have the same label too. but my code doesn't handle this case right now anyway

pg:

> When teaching does it ever come up that rows/columns have duplicate indices ? If that never comes up, we can punt on it and flag it as an unsupported feature if the frontend detects it. For python tutor I have a doc I send users to when they try to do something unsupported ...

sam:

> we only tell students that it's possible, but we try to avoid it in lecture and homework code since it just causes confusion.
> 
> yeah i think we should punt on duplicate labels, especially since i don't think it'll completely break the frontend if we do have them.

**Comment by pgbovine** [comment]
An example of non-unique indexes, i think:
```python
# https://pandas.pydata.org/pandas-docs/stable/user_guide/groupby.html
import pandas as pd
import numpy as np

# non-unique index, explodes
lst = [1, 2, 3, 1, 2, 3]
s = pd.Series([1, 2, 3, 10, 20, 30], lst)
s.groupby(level=0)
```

**Comment by SamLau95** [comment]
@pgbovine says we can do it on the frontend so we don't need to handle on the backend
