### ISSUE TITLE
can you make a test where level != null?

### ISSUE THREAD

**Issue by pgbovine** [SamLau95/pandas_tutor#111]
I see level == null here, can you make a similar-ish test where level isn't null, so that i can see how to handle it on my end?

https://github.com/SamLau95/pandas_tutor/blob/8fd0ed63b50d1b43d1b825895e17d2f1357bf06c/pandas_tutor/tests/e2e_golden/rename_rows.py.golden#L25

**Comment by SamLau95** [comment]
we're just doing rename() using row-to-row mappings directly instead of having a separate `LabelPos` thing. this means we can remove `LabelPos`.
