### ISSUE TITLE
pivot_values_01 - non-existent columns in 'rhs'

### ISSUE THREAD

**Issue by pgbovine** [SamLau95/pandas_tutor#117]
column names like 'A', 'B', 'C' don't exist in rhs table, so my canonicalizer can't find them:
https://github.com/SamLau95/pandas_tutor/blob/152ab1bd488a5a29c821dc7f433a0b99f10fe455/pandas_tutor/tests/e2e_golden/pivot_values_01.py.golden#L60

**Comment by SamLau95** [comment]
this is a bug on my end
