### ISSUE TITLE
groupby tests - non-existent columns in pos

### ISSUE THREAD

**Issue by pgbovine** [SamLau95/pandas_tutor#118]
These columns don't seem to exist, so my canonicalizer script can't find them. they seem to exist within group_data, so i'm not sure whether i'm supposed to look for them in there. we should discuss to clarify!

1) https://github.com/SamLau95/pandas_tutor/blob/152ab1bd488a5a29c821dc7f433a0b99f10fe455/pandas_tutor/tests/e2e_golden/groupby_manual.py.golden#L24

2) https://github.com/SamLau95/pandas_tutor/blob/152ab1bd488a5a29c821dc7f433a0b99f10fe455/pandas_tutor/tests/e2e_golden/groupby_with_groupers_01.py.golden#L24

3) https://github.com/SamLau95/pandas_tutor/blob/152ab1bd488a5a29c821dc7f433a0b99f10fe455/pandas_tutor/tests/e2e_golden/groupby_with_level_01.py.golden#L24

**Comment by SamLau95** [comment]
1. i'll fix this
2. punting, added to limitations (case of grouping with index)
3. punting, same as 2.
