### ISSUE TITLE
add Using mark for stack and unstack

### ISSUE THREAD

**Issue by SamLau95** [SamLau95/pandas_tutor#127]

**Comment by pgbovine** [comment]
is a Using mark necessary, or should the frontend just auto-insert rectangular highlights whenever a row/column index name is being pointed-to with an arrow? i guess it comes down to whether you only want to do it for stack/unstack, or whether you want to do it for everything. e.g., for pivot below, do you want any rectangular highlights?

https://cokapi.com/wst-pg-devel/wst/wsapp/frontend/vis.html#trace=json-test-files/pandas-backend/v2-trace-format/from-sam-github/pivot_columns_01.py.golden.canonicalized

**Comment by SamLau95** [comment]
yeah i think that's a good point. what if we try always creating rectangular highlights in the frontend for row/index levels when they're being moved around? that'll affect stack/unstack/pivot/pivot table.

**Comment by pgbovine** [comment]
k i'll try to handle that on my end then

**Comment by pgbovine** [comment]
some of these don't look so bad without rectangles ... but i guess this is going from an index to a column, so maybe it doesn't count. maybe we should do rectangles only for "index-to-index" moves

https://cokapi.com/wst-pg-devel/wst/wsapp/frontend/vis.html#trace=json-test-files/pandas-backend/v2-trace-format/from-sam-github/reset_index_multi.py.golden.canonicalized

**Comment by pgbovine** [comment]
closed and replacing with https://github.com/SamLau95/pandas_tutor/issues/133

we decided to have sam handle it on the backend instead of philip handling it in the canonicalizer script
