### ISSUE TITLE
is reset_index_multi.py.golden.golden a real test, or a typo?

### ISSUE THREAD

**Issue by pgbovine** [SamLau95/pandas_tutor#129]
should this test case be here, or is it a typo that resulted in an extra file?

https://github.com/SamLau95/pandas_tutor/blob/92fb98a121bd59ada73d692f260a1f636a76776e/pandas_tutor/tests/e2e_golden/reset_index_multi.py.golden.golden#L1

**Comment by SamLau95** [comment]
oops, that's a typo. thanks!
