### ISSUE TITLE
handle non-dataframe objects

### ISSUE THREAD

**Issue by SamLau95** [SamLau95/pandas_tutor#13]
like series, scalars, etc.

```python
import pandas as pd
import io

csv = '''
breed,grooming,food_cost,kids,size
Labrador Retriever,weekly,466.0,high,medium
German Shepherd,weekly,466.0,medium,large
Beagle,daily,324.0,high,small
Golden Retriever,weekly,466.0,high,medium
Yorkshire Terrier,daily,324.0,low,small
Bulldog,weekly,466.0,medium,medium
Boxer,weekly,466.0,high,medium
'''

dogs = pd.read_csv(io.StringIO(csv))

(dogs['food_cost']
)
```

**Comment by pgbovine** [comment]
it'd be good to handle series like dataframes with a warning that it's actually a Series.

then one catch-all idea is to just encode the repr() or str() form of whatever non-dataframe object you encounter and encode it like this (i just made this up):
```
rhs: {
  kind: "unknown",
  type: "< type() of object or something like that >",
  repr: "<repr or str form of object>"
}
```

Then the question is what to do next? you could stop executing the chain at that point and issue a warning and say "returned object isn't a dataframe, stopping now".

**Comment by SamLau95** [comment]
closed by https://github.com/SamLau95/pandas_tutor/pull/21
