### ISSUE TITLE
get pandas_tutor working in-browser with pyodide [in-progress ... notes in this thread]

### ISSUE THREAD

**Issue by pgbovine** [SamLau95/pandas_tutor#130]
e.g., with pyodide: https://github.com/pyodide/pyodide

i've gotten python tutor working with pyodide before, but it has no external library dependencies so it was probably easier.

the dream is to have this working in-browser so that we can remove a lot of the latency and the server restrictions.

a super-stretch goal is to allow users to download .csv/etc. files from the web and *cache them locally* in the browser session so that calling read_csv() etc. again will simply use the local cache.

**Comment by pgbovine** [comment]
JupyterLite is a related project: https://jupyterlite.readthedocs.io/en/latest/

**Comment by pgbovine** [comment]
one concern is exact package versions -- is the exact (or a compatible) version of pandas available within pyodide? if pandas versions differs too much, i'm afraid that your analysis code may break in subtle ways since it deals a lot with pandas internals.

**Comment by pgbovine** [comment]
i tried playing with pyodide live within JupyterLite notebooks:
https://jupyterlite.readthedocs.io/en/latest/_static/lab/index.html

[ another demo site: https://jupyterlite.github.io/demo/lab/index.html ]

it seems like the current pandas version is 1.3.5 when i run:
```python
import pandas as pd
pd.show_versions()
```

i can't seem to install 1.3.1 in your requirements.txt, though.

i can also install libcst fine, it seems:
```python
import micropip
await micropip.install('libcst==0.3.21')
import libcst as cst
from libcst.tool import dump
print(dump(cst.parse_expression("(1 + 2)")))
```

[random note: there's micropip but also piplite ... what's the difference?]

**Comment by pgbovine** [comment]
i also see various discussions about using Emscriptem's in-browser filesystem API through python or js, so we can potentially use that to download and cache .csv files from the web. e.g.,:

- https://github.com/jupyterlite/jupyterlite/blob/main/examples/pyolite/emscripten-filesystem.ipynb
- https://github.com/jupyterlite/jupyterlite/discussions/91

**Comment by pgbovine** [comment]
super-duper stretch goal: with pandastutor running in-browser, we can then make a bookmarklet that enhances the official pandas documentation (or other documentation pages and online textbooks) with a live pandastutor REPL and visualizations!!!

inspired by how they enhanced the numpy documentation:
https://blog.jupyter.org/jupyter-everywhere-f8151c2cc6e8

**Comment by pgbovine** [comment]
see this section and thread for a discussion of how to call python packages (like pandas_tutor hopefully!) directly from JS:
https://blog.pyodide.org/posts/0.19-release/#new-unpackarchive-and-pyimport-apis


> We added new APIs pyodide.unpackArchive and pyodide.pyimport.
> 
> These are part of our goal of encouraging people to develop their Python code for use in Pyodide like normal Python packages and to call into their Python packages directly from JavaScript, rather than using pyodide.runPython.
> 
> Users can develop a Python package, then zip it and install it with pyodide.unpackArchive, import it with pyodide.pyimport and then call their Python functions directly from Javascript.

**Comment by pgbovine** [comment]
aspirational: imagine making a bookmarklet that would enhance stackoverflow questions like these with a live pandastutor widget all without needing a server: https://stackoverflow.com/questions/31306741/unmelt-pandas-dataframe

**Comment by pgbovine** [comment]
i tried installing some packages with micropip in the pyodide REPL:
https://pyodide.org/en/stable/console.html

```python
>>> await micropip.install('typing-extensions==4.1.1')
>>> micropip.list()
Name              | Version | Source
----------------- | ------- | -------
mypy-extensions   | 0.4.3   | pypi
typing-inspect    | 0.7.1   | pypi
libcst            | 0.3.21  | pypi
typing-extensions | 4.1.1   | pyodide
pyyaml            | 6.0     | pyodide
colorful          | 0.5.4   | pypi
prettyprinter     | 0.18.0  | pypi
pygments          | 2.11.2  | pyodide
types-simplejson  | 3.17.1  | pypi
toml              | 0.10.2  | pypi
mypy              | 0.910   | pypi
distutils         | 1.0     | pyodide
micropip          | 0.1     | pyodide
pyparsing         | 3.0.7   | pyodide
packaging         | 21.3    | pyodide
```

These things from https://github.com/SamLau95/pandas_tutor/blob/master/requirements.txt can't be found in micropip:
- docopt
- simplejson
- pympler

If they're pure-python, then maybe we can just inline them into our project's source tree when we build for pyodide. actually it may be a good idea to bundle ALL dependencies into the tree so that we can lock in all the module versions (i.e., vendoring).

**Comment by pgbovine** [comment]
tips for speeding up pyodide load times:
https://emscripten.org/docs/compiling/Deploying-Pages.html

load/run in background with webworkers:
https://pyodide.org/en/stable/usage/webworker.html#using-from-webworker

**Comment by SamLau95** [comment]
we did it!
