### ISSUE TITLE
FYI - try not using prettyprinter outside of sams_scratchpad.py

### ISSUE THREAD

**Issue by pgbovine** [SamLau95/pandas_tutor#138]
it's fine to use this in sams_scratchpad.py when you're developing, but try not to use prettyprinter in the core pandas_tutor analysis files since it bloats up the size of the package in pyodide (because it pulls in a few other package dependencies too). and i don't think we need it normally.

https://github.com/SamLau95/pandas_tutor/blob/4ad0440079408d7e06c3666eccdbaa8c6eab6b87/requirements.txt#L4

**Comment by pgbovine** [comment]
woohoo, the pandas_tutor wheel is about 750k without prettyprinter, and 2MB with it :0

**Comment by SamLau95** [comment]
note to self: fix this by moving prettyprinter into a requirements-dev.txt file
