### ISSUE TITLE
accuracy of different kinds of merges?

### ISSUE THREAD

**Issue by pgbovine** [SamLau95/pandas_tutor#140]
I think some of the merge 'how' parameters might not be handled properly, but i'm not an expert on merges/joins.

See comment before the last line. You can try it out on the staging site too:
https://cokapi.com/wst-pg-devel/wst/wsapp/frontend/vis.html#

```python
import pandas as pd
import io

csv = '''
Name,Sex,Count,Year
Noah,M,18252,2020
Julius,M,960,2020
Karen,M,6,2020
Karen,F,325,2020
Noah,F,305,2020
'''

csv2 = '''
nyt_name,category
Karen,boomer
Julius,mythology
Freya,mythology
'''

baby = pd.read_csv(io.StringIO(csv))
nyt = pd.read_csv(io.StringIO(csv2))

# try how='left' or 'right' or 'inner' or 'outer' to see if it's accurate
baby.merge(nyt, left_on='Name', right_on='nyt_name')
```

**Comment by SamLau95** [comment]
yup, just tried it myself and it looks like there's some buggy behavior for right and outer joins

**Comment by pgbovine** [comment]
cool, yeah with the instant speed of pyodide i was able to wreck-it-ralph better since i just messed around with different parameters to see what happens. if i had to wait 5 seconds between runs, i wouldn't have messed around. ... an even more stretchy goal here is to embed these into pandas API documentation so that users can play around freely with API parameters and see what happens
