### ISSUE TITLE
future! try using pyodide with pandas stack to get everything in-browser

### ISSUE THREAD

**Issue by pgbovine** [SamLau95/pandas_tutor#17]
This may be the way to scale a bunch to bigger datasets!

**Comment by pgbovine** [comment]
also this: https://twitter.com/ethanhs/status/1464308141105967104

**Comment by pgbovine** [comment]
also jupyter-lite as well (jupyter in wasm)

**Comment by SamLau95** [comment]
we've accomplished the dream
