### ISSUE TITLE
create separate dev and prod versions of pandas-tutor pypi package

### ISSUE THREAD

**Issue by pgbovine** [SamLau95/pandas_tutor#173]
The prod one should always point to something like `https://pandastutor.com/js/wsembed.bundle.2021-06-01.js` (or whatever the final URL of the current version of the bundle is) for better reproducibility and stability.

The dev one should always point to `https://cokapi.com/wst-pg-devel/wst/wsapp/frontend/build/wsembed.bundle.js` so that i can easily update it by editing/compiling my frontend code and the user just needs to do `%reload_ext pandas_tutor` in jupyter (with 'disable cache' set in chrome devtools) to instantly see the latest updates.

**Comment by SamLau95** [comment]
from pg: 

btw i've been tweaking the main bundle for doing screencast recordings so if you want a "safe" release to bundle with jupyter plugin, try this one:

https://cokapi.com/wst-pg-devel/wst/wsapp/frontend/build/wsembed.bundle.2022-06-12-release.js
