### ISSUE TITLE
inline all dependencies (except for pandas) into pandas-tutor PyPI package

### ISSUE THREAD

**Issue by pgbovine** [SamLau95/pandas_tutor#176]
Right now you need to install dependencies separately before you can use the pandas-tutor PyPI package in a fresh jupyter notebook.

One idea is to inline everything into the pandas-tutor PyPI package ... I already did this for [the pyodide wheel build](https://github.com/pgbovine/wst/blob/master/wsapp/frontend/js/pyodide/Makefile) so we could do the same thing for the pandas-tutor PyPI package to reduce dependence on external libraries.

Or we could just rely on `requirements.txt` and pin all the versions of dependencies to make that work too.

**Comment by SamLau95** [comment]
i inlined the deps in https://github.com/SamLau95/pandas_tutor/commit/33fe534f2507aa1e5ef13142b3a68b685e93281f
