### ISSUE TITLE
arrows from a cell to a scalar?

### ISSUE THREAD

**Issue by pgbovine** [SamLau95/pandas_tutor#185]
the way this is currently parsed, it seems like you want to point from an entire row to a scalar, then from an entire column to a scalar:

https://github.com/SamLau95/pandas_tutor/blob/df6003047fafdf07d984fd3eb6c5d37fc9f5b91c/pandas_tutor/tests/e2e_golden/iloc_df_into_scalar_01.py.golden#L19

would the more elegant thing be to simply specify an individual cell and point that to the scalar? the wst frontend already supports arrows that originate from an individual table cell. for pandas_tutor, should we make a cell position type that looks something like (for this example):

```json
        {
          "type": "map",
          "from": {
            "type": "axis",
            "anchor": "lhs",
            "select": "cell",
            "row_label": "James Harden",
            "col_label": "Team"
          },
          "to": {
            "type": "scalar",
            "anchor": "rhs"
          }
        }
```

**Comment by pgbovine** [comment]
the same thing happens in this related tests:

https://github.com/SamLau95/pandas_tutor/blob/df6003047fafdf07d984fd3eb6c5d37fc9f5b91c/pandas_tutor/tests/e2e_golden/iloc_df_into_scalar_01.py.golden#L23

(note that for the Series -> scalar arrows it's fine as-is since they only go from a row to a scalar, because a Series doesn't have multiple columns ... it's when there are multiple columns that it gets confusing)

**Comment by SamLau95** [comment]
yeah i was thinking about that and i think it makes sense.

so dataframes->scalar will use `"select": "cell"` but series->scalar will use `"select": "row"`

**Comment by pgbovine** [comment]
sure, sounds good!

btw check this Pega spec out for [cell-to-cell arrows in wst](https://pandastutor.com/playground.html#%7B%0A%20%20%22lang%22%3A%20%22sql%22%2C%0A%20%20%22trace%22%3A%20%5B%0A%20%20%20%20%7B%0A%20%20%20%20%20%20%22tables%22%3A%20%7B%0A%20%20%20%20%20%20%20%20%22lhs%22%3A%20%7B%0A%20%20%20%20%20%20%20%20%20%20%22data%22%3A%20%5B%0A%20%20%20%20%20%20%20%20%20%20%20%20%5B%22LHS%20Labrador%22%2C%20%22weekly%22%2C%20466%2C%20%22high%22%2C%20%22mid%22%5D%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%5B%22LHS%20Shepherd%22%2C%20%22weekly%22%2C%20466%2C%20%22mid%22%2C%20%22large%22%5D%0A%20%20%20%20%20%20%20%20%20%20%5D%2C%0A%20%20%20%20%20%20%20%20%20%20%22row_labels%22%3A%20%5B0%2C%201%5D%2C%0A%20%20%20%20%20%20%20%20%20%20%22col_labels%22%3A%20%5B%22breed%22%2C%20%22groom%22%2C%20%22food%22%2C%20%22kids%22%2C%20%22size%22%5D%0A%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20%20%20%22rhs%22%3A%20%7B%0A%20%20%20%20%20%20%20%20%20%20%22data%22%3A%20%5B%0A%20%20%20%20%20%20%20%20%20%20%20%20%5B%22RHS%20Labrador%22%2C%20%22weekly%22%2C%20466%2C%20%22high%22%2C%20%22mid%22%5D%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%5B%22RHS%20Shepherd%22%2C%20%22weekly%22%2C%20466%2C%20%22mid%22%2C%20%22large%22%5D%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%5B%22RHS%20Beagle%22%2C%20%22daily%22%2C%20324%2C%20%22high%22%2C%20%22small%22%5D%0A%20%20%20%20%20%20%20%20%20%20%5D%2C%0A%20%20%20%20%20%20%20%20%20%20%22row_labels%22%3A%20%5B0%2C%201%2C%202%5D%2C%0A%20%20%20%20%20%20%20%20%20%20%22col_labels%22%3A%20%5B%22breed%22%2C%20%22groom%22%2C%20%22food%22%2C%20%22kids%22%2C%20%22size%22%5D%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20%22expr%22%3A%20%7B%22code%22%3A%20%22%22%7D%2C%0A%0A%20%20%20%20%20%20%22annotations%22%3A%20%5B%0A%20%20%20%20%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%20%20%22type%22%3A%20%22arrow%22%2C%0A%20%20%20%20%20%20%20%20%20%20%22from%22%3A%20%7B%22table%22%3A%20%22lhs%22%2C%20%22row%22%3A%200%2C%20%22col%22%3A%202%7D%2C%0A%20%20%20%20%20%20%20%20%20%20%22to%22%3A%20%7B%22table%22%3A%20%22rhs%22%2C%20%22row%22%3A%201%2C%20%22col%22%3A%203%7D%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%5D%0A%20%20%20%20%7D%0A%20%20%5D%0A%7D)
