### ISSUE TITLE
groupby_into_series should highlight/outline the food_cost column here ...

### ISSUE THREAD

**Issue by pgbovine** [SamLau95/pandas_tutor#27]
does it make sense to highlight/outline the food_cost column here?
https://github.com/SamLau95/pandas_tutor/blob/4cd34e87755d961c252d3ae2ef45f791d6f8ddf4/pandas_tutor/tests/e2e_golden/groupby_into_series.py.golden#L194

**Comment by SamLau95** [comment]
i think so!

**Comment by SamLau95** [comment]
closed by #49
