### ISSUE TITLE
think about whether you want str() or repr() for untracked types

### ISSUE THREAD

**Issue by pgbovine** [SamLau95/pandas_tutor#28]
repr() seems to more literally show what the type is, e.g., it will quote strings and show classes. while str() tries to pretty-print things as a string. i personally feel that repr() is more "literal" since it doesn't try to hide anything from the user. e.g., you know that y is a datetime.datetime type from seeing repr(y), but str(y) could've just been a string you created

```python
$ python3
Python 3.7.4 (v3.7.4:e09359112e, Jul  8 2019, 14:54:52)
[Clang 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from datetime import datetime
>>> x = 'hello'
>>> y = datetime.now()
>>> str(x)
'hello'
>>> repr(x)
"'hello'"
>>> str(y)
'2021-11-17 07:58:14.796483'
>>> repr(y)
'datetime.datetime(2021, 11, 17, 7, 58, 14, 796483)'
```

**Comment by SamLau95** [comment]
i switched to `repr` in https://github.com/SamLau95/pandas_tutor/pull/30
