### ISSUE TITLE
how come type is spelled "type_" here in ParseError?

### ISSUE THREAD

**Issue by pgbovine** [SamLau95/pandas_tutor#34]
https://github.com/SamLau95/pandas_tutor/blob/8610da45cc651cb2ade990e21e5a4c7605e2c18d/pandas_tutor/tests/e2e_golden/error_syntax_01.py.golden#L2

**Comment by SamLau95** [comment]
ah that's my bad. internally i have different data types for parse results and here i just returned the internal type. i'll make syntax errors more consistent with the other output types.
