### ISSUE TITLE
make a distinction between run-time errors before chain that you're analyzing and during

### ISSUE THREAD

**Issue by pgbovine** [SamLau95/pandas_tutor#36]
Right now this code_step is indistinguishable from errors in the chain you're analyzing:
https://github.com/SamLau95/pandas_tutor/blob/8610da45cc651cb2ade990e21e5a4c7605e2c18d/pandas_tutor/tests/e2e_golden/error_runtime_in_setup.py.golden#L4

Can we have this be a different type altogether, like type = "RuntimeErrorBeforeChain" or something? and instead of code_step, have it be code, just like ParseError?

Errors in chain:
https://github.com/SamLau95/pandas_tutor/blob/master/pandas_tutor/tests/e2e_golden/error_runtime_in_chain_01.py.golden
https://github.com/SamLau95/pandas_tutor/blob/master/pandas_tutor/tests/e2e_golden/error_runtime_in_chain_02.py.golden

**Comment by pgbovine** [comment]
even better, if you can report a line number for run-time error before chain (just like for syntax error) that would be great. that could be highlighted in the code editor itself as an error

[update: no need for line numbers if that's too tricky to get -- just a nice error string for user is fine]

**Comment by pgbovine** [comment]
i don't think this has been resolved yet, right? i saw you patched up some other error messages, but maybe this one is still unresolved?

for mario, if there's an error during the chained call, there's actually an "lhs" table (since lhs exists, but there's an error in the operation to go from lhs -> rhs). but if there's a run-time error in the setup code, there's no lhs.

**Comment by pgbovine** [comment]
[not a huge rush on this, i was just looking over all the new error-handling stuff just now]

**Comment by SamLau95** [comment]
nope i haven't gotten to this yet. should be coming out soon.
