### ISSUE TITLE
add tests with various errors and the appropriate JSON outputs for errors

### ISSUE THREAD

**Issue by pgbovine** [SamLau95/pandas_tutor#4]
e.g.,:
- syntax errors
- runtime errors that occur *before* the final expression we're analyzing
- runtime errors that occur during one stage of the expression we're analyzing (ideally it would produce partial results for stages before the error so that users can see what led up to that error)

**Comment by pgbovine** [comment]
related: create a coherent json error output for all of those kinds of errors (cc: @SamLau95 ). at a high level, there are two kinds of errors worth distinguishing:

- errors that occur before any data frame is produced (these include both syntax errors and runtime errors in code leading up to the last line) ... this should result in a trace with only one object -- an error object -- and no data frames.
- errors that occur during some stage of the chained expression we're analyzing -- this error object should be attached to that stage, so that all the stages before can be properly displayed. likely that stage will have a proper lhs too, since the error is probably in processing lhs

**Comment by SamLau95** [comment]
closed in https://github.com/SamLau95/pandas_tutor/pull/29 and https://github.com/SamLau95/pandas_tutor/pull/30
