### ISSUE TITLE
groupby with multi-keys sometimes breaks (haven't investigated in depth yet)

### ISSUE THREAD

**Issue by pgbovine** [SamLau95/pandas_tutor#72]
Some example test cases where it breaks:

```python
# https://pandas.pydata.org/pandas-docs/stable/user_guide/groupby.html
import pandas as pd
import numpy as np
np.random.seed(0)

arrays = [
    ["bar", "bar", "baz", "baz", "foo", "foo", "qux", "qux"],
    ["one", "two", "one", "two", "one", "two", "one", "two"],
]
index = pd.MultiIndex.from_arrays(arrays, names=["first", "second"])

df = pd.DataFrame({"A": [1, 1, 1, 1, 2, 2, 3, 3], "B": np.arange(8)}, index=index)

df.groupby([pd.Grouper(level=1), "A"])
```

```python
# https://pandas.pydata.org/pandas-docs/stable/user_guide/groupby.html
import pandas as pd
import numpy as np
np.random.seed(0)

df = pd.DataFrame(
    {
        "A": ["foo", "bar", "foo", "bar", "foo", "bar", "foo", "foo"],
        "B": ["one", "one", "two", "three", "two", "two", "one", "three"],
        "C": np.random.randn(8),
        "D": np.random.randn(8),
    }
)

df2 = df.set_index(["A", "B"])
df2.groupby(level=df2.index.names.difference(["B"]))
```

a variant of the prior example:

```python
# https://pandas.pydata.org/pandas-docs/stable/user_guide/groupby.html
import pandas as pd
import numpy as np
np.random.seed(0)

df = pd.DataFrame(
    {
        "A": ["foo", "bar", "foo", "bar", "foo", "bar", "foo", "foo"],
        "B": ["one", "one", "two", "three", "two", "two", "one", "three"],
        "C": np.random.randn(8),
        "D": np.random.randn(8),
    }
)
df2 = df.set_index(["A", "B"])
grouped = df2.groupby(level=df2.index.names.difference(["B"]))
grouped.sum()
```

**Comment by pgbovine** [comment]
not sure if this is a multi-key, but get_group() breaks:
```python
# https://pandas.pydata.org/pandas-docs/stable/user_guide/groupby.html
import pandas as pd
import numpy as np

df3 = pd.DataFrame({"X": ["A", "B", "A", "B"], "Y": [1, 4, 3, 2]})
df3.groupby(["X"]).get_group("A")
```

[update: this currently passes thru canonicalizer script but with a warning i think]

**Comment by SamLau95** [comment]
i think these examples really have to do with the parser not handling nested function calls properly rather than groupby not working.

right now, if we give `df.groupby([pd.Grouper(level=1), "A"])` to the parser, it thinks that pd.Grouper is the first step in the chain, and df.groupby is the second step. it should instead recognize that df.groupby is the top-level function chain and treat nested function calls as arguments (that should be parsed differently) rather than recursing into them.

**Comment by pgbovine** [comment]
cool, i'll note this under the no-nested-calls limitations and punt to v2 ... we can discuss more later so we can figure out how to alert users to when there might be a nested call

**Comment by pgbovine** [comment]
@SamLau95 -- can you check out these tests again after you committed this change https://github.com/SamLau95/pandas_tutor/pull/82 ?

they don't necessarily need to work right now (we can punt to v2) but it'd be good to scan through their traces to make sure it makes sense given your new parser changes

**Comment by pgbovine** [comment]
added to my pg test suite and defer for now

**Comment by SamLau95** [comment]
okay, most of these work properly after https://github.com/SamLau95/pandas_tutor/pull/103 .

the `get_group` example doesn't error, but doesn't return the correct trace. i consider this a special case of the more general problem that we just assume the first function call after `groupby` is always an aggregation, so i'm closing this in favor of https://github.com/SamLau95/pandas_tutor/issues/104
