### ISSUE TITLE
enhance 'code' field with the start/end positions of the current expression

### ISSUE THREAD

**Issue by pgbovine** [SamLau95/pandas_tutor#8]
In a chain like this, I see stuff like:
```
    "type": "Subscript",
    "code_step": "dogs.sort_values('kids').loc[0:6]",
```

I think the ".loc[0:6]" is what's being visualized in that step, so if you could augment that field with starting and ending positions of that substring, then we can highlight/bold it or something. otherwise it's not clear what code is running in that step

**Comment by SamLau95** [comment]
done in https://github.com/SamLau95/pandas_tutor/pull/38
